import { Inter, Oswald } from 'next/font/google';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
const inter = Oswald({ subsets: ['latin'] });

export const metadata = {
  title: 'E-Commerce Shoe Store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
