import { Inter, Oswald, Urbanist } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
// const inter = Oswald({ subsets: ['latin'] });
const inter = Urbanist({ subsets: ['latin'] });

export const metadata = {
  title: 'E-Commerce Shoe Store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
